# Generated by Django 2.0.2 on 2018-03-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('guess', models.CharField(max_length=32)),
                ('correct_value_and_position', models.IntegerField()),
                ('correct_value_not_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('pattern', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('STARTED', 'Started'), ('ERROR', 'Error'), ('COMPLETED', 'Completed')], default='NEW', max_length=32)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Game'),
        ),
    ]
