# Generated by Django 2.0.2 on 2018-03-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0002_auto_20180306_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='attempts',
            new_name='num_attempts',
        ),
    ]
